import { MetaMaskProvider } from "metamask-react";
import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <MetaMaskProvider>
      <Head>
        <title>Princeton Immutable Diploma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nassau.jpeg" />
      </Head>
      <Component {...pageProps} />
      {/* <footer className={"fixed bottom-0 py-1 font-light mx-auto"}>
        {"Created by Quinn Donohue and Dane Jacobson '22."}
      </footer> */}
    </MetaMaskProvider>
  );
}

export default MyApp;
