import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Metamask from "../components/crypto/Metamask";
import Landing from "../components/landing/landing";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Princeton Immutable Diploma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nassau.jpeg" />
      </Head>

      <div className="flex flex-row justify-center items-center w-full h-screen">
        <Landing />
      </div>

      <footer className={"my-2 font-light mx-auto"}>
        Created by Quinn Donohue and Dane Jacobson '22.
      </footer>
    </div>
  );
};

export default Home;
